function ac = ac_setup(size)

ac.layers = {};
ac.error = [];
ac.mse = [];

ac.layers{1} = struct('weights', (rand(size(2), size(1) ) - 0.5) * 0.01 * 2, ...
                      'v_mem', [], ...
                      'spikes', [], ...
                      'v_mem_prev', [], ...
                      'dL_dW', [], ...
                      'm1', [] , ... 
                      'm2', [], ...
                      'dvmem_dW_prev', []);
                  
ac.layers{2} = struct('weights', (rand(size(3), size(2)) - 0.5) * 0.01 * 2, ...
                      'v_mem', [], ...
                      'spikes', [], ...
                      'v_mem_prev', [], ...
                      'dL_dW', [], ...
                      'm1', [] , ... 
                      'm2', [], ...
                      'dvmem_dW_prev', [], ...
                      'dz_dW', []);

end